"""public schema baseline

Revision ID: public_schema_baseline
Revises:
Create Date: 2026-07-24 08:40:03.179995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'public_schema_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentteams_integration_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False, comment='AgentTeams 部署地址或同站反代路径'),
    sa.Column('integration_secret', sa.Text(), nullable=False, comment='加密存储的 AgentTeams 集成密钥'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用 AgentTeams 集成'),
    sa.Column('upsell_title', sa.String(length=100), nullable=True, comment='未配置提示标题'),
    sa.Column('upsell_message', sa.Text(), nullable=True, comment='未配置提示说明'),
    sa.Column('demo_asset_url', sa.String(length=500), nullable=True, comment='演示资源 URL'),
    sa.Column('cta_label', sa.String(length=100), nullable=True, comment='行动按钮文案'),
    sa.Column('cta_url', sa.String(length=500), nullable=True, comment='行动按钮 URL'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_key', sa.String(length=50), nullable=False, comment='分类key'),
    sa.Column('category_name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('icon', sa.String(length=10), nullable=True, comment='图标'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='颜色'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='描述'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('group_key', sa.String(length=50), nullable=True, comment='分组标识'),
    sa.Column('report_type', sa.String(length=20), nullable=True, comment='OCR报告类型: lab/exam/pathology'),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_key')
    )
    op.create_index(op.f('ix_image_category_category_id'), 'image_category', ['category_id'], unique=False)
    op.create_table('knowledge_config',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('config_description', sa.String(length=200), nullable=True, comment='配置说明'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_index('idx_knowledge_config_key', 'knowledge_config', ['config_key'], unique=False)
    op.create_index(op.f('ix_knowledge_config_config_id'), 'knowledge_config', ['config_id'], unique=False)
    op.create_table('llm_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键，如 consultation_api_key'),
    sa.Column('config_value', sa.Text(), nullable=False, comment='配置值，API Key 等敏感字段加密存储'),
    sa.Column('config_group', sa.String(length=50), nullable=False, comment='配置组: consultation/interpretation/ocr'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='中文显示名'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置说明'),
    sa.Column('is_secret', sa.Boolean(), nullable=True, comment='是否敏感字段，API 返回时掩码处理'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否生效: true=数据库值优先, false=使用环境变量'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('login_account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('account_name', sa.String(length=100), nullable=True, comment='账号显示名称'),
    sa.Column('account_type', sa.String(length=20), nullable=True, comment='账号类型: admin/user'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: active/inactive'),
    sa.Column('wechat_nickname', sa.String(length=100), nullable=True, comment='微信昵称'),
    sa.Column('wechat_avatar', sa.String(length=255), nullable=True, comment='微信头像URL'),
    sa.Column('data_sharing_enabled', sa.Boolean(), nullable=True, comment='是否允许数据分享'),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True, comment='是否接收系统通知'),
    sa.Column('email_notification', sa.Boolean(), nullable=True, comment='是否接收邮件通知'),
    sa.Column('sms_notification', sa.Boolean(), nullable=True, comment='是否接收短信通知'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_login_account_account_id'), 'login_account', ['account_id'], unique=False)
    op.create_table('medical_index',
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('index_name', sa.String(length=100), nullable=False, comment='指标名称'),
    sa.Column('index_unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('reference_min', sa.Numeric(precision=10, scale=2), nullable=True, comment='参考值最小值'),
    sa.Column('reference_max', sa.Numeric(precision=10, scale=2), nullable=True, comment='参考值最大值'),
    sa.Column('index_type', sa.String(length=50), nullable=True, comment='指标类型'),
    sa.Column('is_chart', sa.Boolean(), nullable=True, comment='是否图表展示'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_edit', sa.Boolean(), nullable=True, comment='是否可编辑'),
    sa.Column('index_code', sa.String(length=50), nullable=True, comment='指标编码: WBC, RBC, GLU'),
    sa.Column('index_name_en', sa.String(length=100), nullable=True, comment='英文名称: White Blood Cell'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='指标分类，关联 image_category.category_key'),
    sa.Column('sub_category', sa.String(length=50), nullable=True, comment='子分类: 红细胞系、白细胞系'),
    sa.Column('unit_type', sa.String(length=20), nullable=True, comment='单位类型: concentration, ratio'),
    sa.Column('reference_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{"adult": {"min": 4, "max": 10}}'),
    sa.Column('match_count', sa.Integer(), nullable=True, comment='成功匹配次数'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='系统内置指标不可删除'),
    sa.PrimaryKeyConstraint('index_id'),
    sa.UniqueConstraint('index_code')
    )
    op.create_index('idx_medical_index_active', 'medical_index', ['is_active'], unique=False)
    op.create_index('idx_medical_index_category', 'medical_index', ['category'], unique=False)
    op.create_index('idx_medical_index_code', 'medical_index', ['index_code'], unique=False)
    op.create_index(op.f('ix_medical_index_index_id'), 'medical_index', ['index_id'], unique=False)
    op.create_table('knowledge_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_expanded', sa.Boolean(), nullable=True, comment='是否展开'),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='账号ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_category.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index('idx_knowledge_category_account', 'knowledge_category', ['account_id'], unique=False)
    op.create_index('idx_knowledge_category_parent', 'knowledge_category', ['parent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_category_category_id'), 'knowledge_category', ['category_id'], unique=False)
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='通知类型: system/consultation/report/reminder'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('is_read', sa.Boolean(), nullable=True, comment='是否已读'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='额外数据'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('idx_notification_account_read', 'notification', ['account_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notification_notification_id'), 'notification', ['notification_id'], unique=False)
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False, comment='患者姓名（加密存储）'),
    sa.Column('patient_phone', sa.String(length=200), nullable=True, comment='患者电话（加密存储）'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别: male/female/unknown'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('id_card', sa.String(length=200), nullable=True, comment='身份证号（加密存储）'),
    sa.Column('id_card_hash', sa.String(length=64), nullable=True, comment='身份证哈希索引（查重用）'),
    sa.Column('emergency_contact', sa.String(length=200), nullable=True, comment='紧急联系人（加密存储）'),
    sa.Column('emergency_phone', sa.String(length=200), nullable=True, comment='紧急联系电话（加密存储）'),
    sa.Column('medical_history', sa.Text(), nullable=True, comment='既往病史'),
    sa.Column('allergies', sa.Text(), nullable=True, comment='过敏史'),
    sa.Column('current_medications', sa.Text(), nullable=True, comment='当前用药'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('is_primary', sa.Boolean(), nullable=True, comment='是否主患者'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index(op.f('ix_patient_id_card_hash'), 'patient', ['id_card_hash'], unique=True)
    op.create_index(op.f('ix_patient_patient_id'), 'patient', ['patient_id'], unique=False)
    op.create_table('user_favorite_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=True, comment='自定义排序'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['medical_index.index_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_favorite_unique', 'user_favorite_index', ['account_id', 'index_id'], unique=True)
    op.create_table('wechat_binding',
    sa.Column('binding_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=100), nullable=False, comment='微信OpenID'),
    sa.Column('unionid', sa.String(length=100), nullable=True, comment='微信UnionID'),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ),
    sa.PrimaryKeyConstraint('binding_id'),
    sa.UniqueConstraint('openid')
    )
    op.create_index(op.f('ix_wechat_binding_binding_id'), 'wechat_binding', ['binding_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True, comment='对话标题（患者姓名 + 会诊摘要）'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True, comment='oncopath 扩展：关联患者'),
    sa.Column('is_archived', sa.Boolean(), nullable=False, comment='是否归档'),
    sa.Column('is_review_mode', sa.Boolean(), nullable=False, comment='评审模式'),
    sa.Column('share_token', sa.String(length=20), nullable=True, comment='分享令牌'),
    sa.Column('share_password', sa.String(length=100), nullable=True, comment='分享密码(bcrypt哈希)'),
    sa.Column('share_expire_at', sa.DateTime(), nullable=True, comment='分享过期时间'),
    sa.Column('category', sa.String(length=20), nullable=True, comment='分类'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='new/analyzing/completed/error'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['login_account.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_category'), 'conversations', ['category'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_patient_id'), 'conversations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_conversations_share_token'), 'conversations', ['share_token'], unique=True)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_user_updated', 'conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('follow_up_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='提醒标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('reminder_date', sa.Date(), nullable=False, comment='提醒日期'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: pending/sent/confirmed/expired'),
    sa.Column('source_type', sa.String(length=30), nullable=True, comment='来源: manual/interpretation/consultation'),
    sa.Column('source_id', sa.Integer(), nullable=True, comment='关联来源ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_follow_up_patient_status', 'follow_up_reminder', ['patient_id', 'status'], unique=False)
    op.create_index(op.f('ix_follow_up_reminder_id'), 'follow_up_reminder', ['id'], unique=False)
    op.create_table('image_report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='报告标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类key'),
    sa.Column('hospital', sa.String(length=100), nullable=True, comment='医院代码'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='科室代码'),
    sa.Column('image_type', sa.String(length=20), nullable=True, comment='文件类型: jpeg, png, pdf'),
    sa.Column('image_size', sa.Integer(), nullable=True, comment='文件大小(字节)'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='文件内容SHA-256哈希(去重键)'),
    sa.Column('image_path', sa.String(length=500), nullable=True, comment='文件存储路径(迁移后使用)'),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True, comment='缩略图存储路径'),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='PDF页数，图片时为null'),
    sa.Column('ocr_text', sa.Text(), nullable=True, comment='OCR识别的原始文本'),
    sa.Column('ocr_status', sa.String(length=20), nullable=True, comment='OCR状态: pending, processing, completed, failed'),
    sa.Column('ocr_error', sa.Text(), nullable=True, comment='OCR错误信息'),
    sa.Column('matched_count', sa.Integer(), nullable=True, comment='匹配成功的指标数'),
    sa.Column('total_count', sa.Integer(), nullable=True, comment='识别的指标总数'),
    sa.Column('matching_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='匹配详情JSON'),
    sa.Column('llm_raw_response', sa.Text(), nullable=True, comment='LLM原始响应（用于调试）'),
    sa.Column('report_type', sa.String(length=20), nullable=True, comment='报告类型: lab/exam/pathology'),
    sa.Column('related_check_id', sa.Integer(), nullable=True, comment='关联的检验记录ID(medical_check)'),
    sa.Column('related_exam_id', sa.Integer(), nullable=True, comment='关联的检查记录ID(medical_exam)'),
    sa.Column('related_pathology_id', sa.Integer(), nullable=True, comment='关联的病理记录ID(pathology_report)'),
    sa.Column('extracted_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='LLM提取的结构化信息(JSON)'),
    sa.Column('capture_date', sa.Date(), nullable=True, comment='检查日期'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签，逗号分隔'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('is_private', sa.Boolean(), nullable=True, comment='是否私有'),
    sa.Column('is_important', sa.Boolean(), nullable=True, comment='是否重要'),
    sa.Column('upload_date', sa.DateTime(), nullable=True, comment='上传时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('idx_image_report_dedup', 'image_report', ['patient_id', 'account_id', 'category', 'content_hash'], unique=False)
    op.create_index('idx_image_report_patient_category', 'image_report', ['patient_id', 'category'], unique=False)
    op.create_index('idx_image_report_patient_ocr', 'image_report', ['patient_id', 'ocr_status'], unique=False)
    op.create_index(op.f('ix_image_report_report_id'), 'image_report', ['report_id'], unique=False)
    op.create_table('knowledge_document',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('doc_name', sa.String(length=200), nullable=False, comment='文档名称'),
    sa.Column('doc_description', sa.Text(), nullable=True, comment='文档描述'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件相对路径（相对于 STORAGE_PATH）'),
    sa.Column('file_name', sa.String(length=200), nullable=True, comment='文件名'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件类型'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='文件哈希(SHA-256)'),
    sa.Column('preview_path', sa.String(length=500), nullable=True, comment='预览路径'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI生成摘要'),
    sa.Column('summary_status', sa.String(length=20), nullable=True, comment='摘要状态: pending/completed/failed'),
    sa.Column('download_count', sa.Integer(), nullable=True, comment='下载次数'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='查看次数'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
    sa.Column('tags', sa.Text(), nullable=True, comment='标签'),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='账号ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_category.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('doc_id'),
    sa.UniqueConstraint('account_id', 'file_hash', name='uq_knowledge_doc_account_hash')
    )
    op.create_index('idx_knowledge_document_account', 'knowledge_document', ['account_id'], unique=False)
    op.create_index('idx_knowledge_document_category', 'knowledge_document', ['category_id'], unique=False)
    op.create_index(op.f('ix_knowledge_document_doc_id'), 'knowledge_document', ['doc_id'], unique=False)
    op.create_table('medical_check',
    sa.Column('medical_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medical_date', sa.Date(), nullable=False, comment='检查日期'),
    sa.Column('hospital', sa.String(length=100), nullable=True, comment='医院'),
    sa.Column('comment', sa.Text(), nullable=True, comment='备注'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='报告分类，关联 image_category.category_key'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True, comment='AI解读内容(Markdown)'),
    sa.Column('interpretation_at', sa.DateTime(), nullable=True, comment='AI解读时间'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('medical_id')
    )
    op.create_index('idx_medical_check_patient_date', 'medical_check', ['patient_id', 'medical_date'], unique=False)
    op.create_index(op.f('ix_medical_check_medical_id'), 'medical_check', ['medical_id'], unique=False)
    op.create_table('medical_exam',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medical_date', sa.Date(), nullable=True, comment='检查日期'),
    sa.Column('hospital', sa.String(length=100), nullable=True, comment='医院'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='报告标题'),
    sa.Column('exam_type', sa.String(length=50), nullable=True, comment='检查类型'),
    sa.Column('exam_info', sa.Text(), nullable=True, comment='检查所见'),
    sa.Column('exam_diag', sa.Text(), nullable=True, comment='诊断意见'),
    sa.Column('comment', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True, comment='AI解读内容(Markdown)'),
    sa.Column('interpretation_at', sa.DateTime(), nullable=True, comment='AI解读时间'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_index('idx_medical_exam_patient_date', 'medical_exam', ['patient_id', 'medical_date'], unique=False)
    op.create_index(op.f('ix_medical_exam_exam_id'), 'medical_exam', ['exam_id'], unique=False)
    op.create_table('medical_record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('record_name', sa.String(length=100), nullable=True, comment='记录名称'),
    sa.Column('record_date', sa.Date(), nullable=True, comment='记录日期'),
    sa.Column('record_info', sa.Text(), nullable=True, comment='记录内容'),
    sa.Column('record_type', sa.String(length=50), nullable=True, comment='记录类型'),
    sa.Column('patient_status', sa.String(length=50), nullable=True, comment='患者状态'),
    sa.Column('comment', sa.Text(), nullable=True, comment='备注'),
    sa.Column('record_drug', sa.Text(), nullable=True, comment='用药记录'),
    sa.Column('hospital', sa.String(length=100), nullable=True, comment='医院'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_medical_record_patient_id'), 'medical_record', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_record_record_id'), 'medical_record', ['record_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='患者ID'),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='账号ID'),
    sa.Column('medication_name', sa.String(length=200), nullable=False, comment='药品名称'),
    sa.Column('generic_name', sa.String(length=200), nullable=True, comment='通用名'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类: 化疗/靶向/免疫/支持/止痛/其他'),
    sa.Column('dosage', sa.String(length=100), nullable=True, comment='剂量(如: 5mg)'),
    sa.Column('frequency', sa.String(length=100), nullable=True, comment='用药频率(如: 每日2次)'),
    sa.Column('route', sa.String(length=50), nullable=True, comment='给药途径(如: 口服/静脉)'),
    sa.Column('duration', sa.String(length=100), nullable=True, comment='用药时长(如: 14天)'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期(NULL=持续用药)'),
    sa.Column('is_ongoing', sa.Boolean(), nullable=True, comment='是否持续用药中'),
    sa.Column('prescriber', sa.String(length=100), nullable=True, comment='开药医生'),
    sa.Column('hospital', sa.String(length=100), nullable=True, comment='开药医院'),
    sa.Column('source', sa.String(length=20), nullable=True, comment='来源: manual/ocr/prescription'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: active/discontinued/completed'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('side_effects', sa.Text(), nullable=True, comment='副作用记录'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medications_account', 'medications', ['account_id'], unique=False)
    op.create_index('idx_medications_patient_status', 'medications', ['patient_id', 'status'], unique=False)
    op.create_index('idx_medications_start_date', 'medications', ['start_date'], unique=False)
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_table('pathology_report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('report_title', sa.String(length=200), nullable=True, comment='报告标题'),
    sa.Column('report_date', sa.Date(), nullable=True, comment='报告日期'),
    sa.Column('hospital', sa.String(length=100), nullable=True, comment='医院'),
    sa.Column('comment', sa.Text(), nullable=True, comment='备注'),
    sa.Column('image_path', sa.String(length=500), nullable=True, comment='图片文件存储路径'),
    sa.Column('image_type', sa.String(length=20), nullable=True, comment='文件类型: jpeg, png, pdf'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True, comment='病理诊断'),
    sa.Column('cancer_type', sa.String(length=100), nullable=True, comment='癌种/肿瘤类型'),
    sa.Column('stage', sa.String(length=50), nullable=True, comment='临床分期(如 IIIA期)'),
    sa.Column('histology_type', sa.String(length=100), nullable=True, comment='组织学类型(如 腺癌/鳞癌)'),
    sa.Column('immunohistochemistry', sa.Text(), nullable=True, comment='免疫组化结果'),
    sa.Column('gene_testing', sa.Text(), nullable=True, comment='基因检测信息'),
    sa.Column('interpretation', sa.Text(), nullable=True, comment='AI解读内容(Markdown)'),
    sa.Column('interpretation_at', sa.DateTime(), nullable=True, comment='AI解读时间'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_pathology_report_patient_id'), 'pathology_report', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pathology_report_report_id'), 'pathology_report', ['report_id'], unique=False)
    op.create_table('prompt_config',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_content_config', sa.Text(), nullable=False),
    sa.Column('time_range_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('record_summary',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='患者ID'),
    sa.Column('summary_type', sa.String(length=20), nullable=False, comment='概要类型: treatment/medication_record/status'),
    sa.Column('period_start', sa.Date(), nullable=False, comment='概要时段起始'),
    sa.Column('period_end', sa.Date(), nullable=False, comment='概要时段结束'),
    sa.Column('summary_text', sa.Text(), nullable=False, comment='概要内容'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='来源: rule_template/llm_generated'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft/confirmed'),
    sa.Column('source_record_count', sa.Integer(), nullable=True, comment='生成时涵盖的原始记录数'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('patient_id', 'summary_type', 'period_start', 'period_end', name='uq_record_summary_patient_type_period')
    )
    op.create_index(op.f('ix_record_summary_summary_id'), 'record_summary', ['summary_id'], unique=False)
    op.create_table('share_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False, comment='分享令牌'),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False, comment='分享内容类型'),
    sa.Column('content_id', sa.Integer(), nullable=False, comment='内容ID'),
    sa.Column('max_access_count', sa.Integer(), nullable=True, comment='最大访问次数'),
    sa.Column('current_access_count', sa.Integer(), nullable=True, comment='当前访问次数'),
    sa.Column('expire_hours', sa.Integer(), nullable=True, comment='有效期(小时)'),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment='过期时间（冗余字段，避免每次计算）'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_token_id'), 'share_token', ['id'], unique=False)
    op.create_index(op.f('ix_share_token_token'), 'share_token', ['token'], unique=True)
    op.create_table('timeline_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False, comment='事件类型: medical/life'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类: surgery/chemotherapy/diagnosis/mood/etc'),
    sa.Column('event_date', sa.Date(), nullable=False, comment='事件日期'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('icon_type', sa.String(length=50), nullable=True, comment='图标类型'),
    sa.Column('color_theme', sa.String(length=20), nullable=True, comment='颜色主题'),
    sa.Column('is_private', sa.Boolean(), nullable=True, comment='是否私密'),
    sa.Column('related_report_id', sa.Integer(), nullable=True, comment='关联报告ID'),
    sa.Column('related_indicators', sa.JSON(), nullable=True, comment='关联指标ID列表'),
    sa.Column('medical_details', sa.JSON(), nullable=True, comment='医疗事件详情'),
    sa.Column('life_details', sa.JSON(), nullable=True, comment='生活事件详情'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_timeline_events_event_id'), 'timeline_events', ['event_id'], unique=False)
    op.create_index('ix_timeline_events_patient_date', 'timeline_events', ['patient_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_timeline_events_patient_id'), 'timeline_events', ['patient_id'], unique=False)
    op.create_table('user_index_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=False, comment='组合名称'),
    sa.Column('index_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='有序指标ID数组，如 [3, 7, 12]'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_index_group_unique', 'user_index_group', ['account_id', 'patient_id', 'group_name'], unique=True)
    op.create_table('consultation_external_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_conversation_id', sa.String(length=100), nullable=False),
    sa.Column('external_session_id', sa.String(length=100), nullable=True),
    sa.Column('external_share_token', sa.String(length=200), nullable=True),
    sa.Column('embed_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consultation_external_provider_status', 'consultation_external_sessions', ['provider', 'status'], unique=False)
    op.create_index(op.f('ix_consultation_external_sessions_conversation_id'), 'consultation_external_sessions', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_consultation_external_sessions_id'), 'consultation_external_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_consultation_external_sessions_provider'), 'consultation_external_sessions', ['provider'], unique=False)
    op.create_index(op.f('ix_consultation_external_sessions_status'), 'consultation_external_sessions', ['status'], unique=False)
    op.create_table('knowledge_access_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True, comment='账号ID'),
    sa.Column('access_type', sa.String(length=20), nullable=True, comment='访问类型: view, download'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('access_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='访问时间'),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doc_id'], ['knowledge_document.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_knowledge_access_log_account', 'knowledge_access_log', ['account_id'], unique=False)
    op.create_index('idx_knowledge_access_log_doc', 'knowledge_access_log', ['doc_id'], unique=False)
    op.create_index(op.f('ix_knowledge_access_log_log_id'), 'knowledge_access_log', ['log_id'], unique=False)
    op.create_table('leader_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True, comment='oncopath 扩展'),
    sa.Column('user_message', sa.Text(), nullable=False, comment='自动收集的病历上下文'),
    sa.Column('state', sa.String(length=20), nullable=True, comment='idle/assessing/questioning/forming_team/web_search/monitoring/summarizing/completed/stopped/failed'),
    sa.Column('assessment_score', sa.Integer(), nullable=True, comment='0-100'),
    sa.Column('risk_level', sa.String(length=10), nullable=True, comment='low/medium/high'),
    sa.Column('selected_agents', sa.String(length=500), nullable=True, comment='逗号分隔的专家 ID'),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('stop_requested', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leader_sessions_conversation_id'), 'leader_sessions', ['conversation_id'], unique=False)
    op.create_index('ix_leader_sessions_conversation_state', 'leader_sessions', ['conversation_id', 'state'], unique=False)
    op.create_index(op.f('ix_leader_sessions_id'), 'leader_sessions', ['id'], unique=False)
    op.create_index('ix_leader_sessions_patient_id', 'leader_sessions', ['patient_id'], unique=False)
    op.create_table('medical_check_detail',
    sa.Column('medical_detail_id', sa.Integer(), nullable=False),
    sa.Column('medical_id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=True, comment='关联标准指标ID'),
    sa.Column('index_name', sa.String(length=100), nullable=False, comment='指标名称'),
    sa.Column('index_value', sa.String(length=50), nullable=True, comment='指标值'),
    sa.Column('index_unit', sa.String(length=20), nullable=True, comment='单位'),
    sa.Column('reference_value', sa.String(length=50), nullable=True, comment='参考值'),
    sa.Column('index_status', sa.String(length=20), nullable=True, comment='状态: normal/abnormal'),
    sa.ForeignKeyConstraint(['index_id'], ['medical_index.index_id'], ),
    sa.ForeignKeyConstraint(['medical_id'], ['medical_check.medical_id'], ),
    sa.PrimaryKeyConstraint('medical_detail_id')
    )
    op.create_index('idx_medical_check_detail_index_id', 'medical_check_detail', ['index_id'], unique=False)
    op.create_index('idx_medical_check_detail_medical_id', 'medical_check_detail', ['medical_id'], unique=False)
    op.create_index(op.f('ix_medical_check_detail_medical_detail_id'), 'medical_check_detail', ['medical_detail_id'], unique=False)
    op.create_index('ix_medical_check_detail_status', 'medical_check_detail', ['index_status'], unique=False)
    op.create_table('medication_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=50), nullable=True),
    sa.Column('time_slot', sa.String(length=20), nullable=True, comment='时段: morning/afternoon/evening/bedtime'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('actual_time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['login_account.account_id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_log_account_id'), 'medication_log', ['account_id'], unique=False)
    op.create_index(op.f('ix_medication_log_id'), 'medication_log', ['id'], unique=False)
    op.create_index('ix_medication_log_med_date', 'medication_log', ['medication_id', 'scheduled_date'], unique=False)
    op.create_index('ix_medication_log_med_date_slot', 'medication_log', ['medication_id', 'scheduled_date', 'time_slot'], unique=False)
    op.create_index('ix_medication_log_patient_date', 'medication_log', ['patient_id', 'scheduled_date'], unique=False)
    op.create_table('ocr_review_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False, comment='报告ID'),
    sa.Column('report_type', sa.String(length=20), nullable=False, comment='报告类型: lab/exam/pathology'),
    sa.Column('field_name', sa.String(length=100), nullable=False, comment='被修正的字段名'),
    sa.Column('original_value', sa.Text(), nullable=True, comment='OCR原始值'),
    sa.Column('corrected_value', sa.Text(), nullable=True, comment='用户修正值'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审查时间'),
    sa.ForeignKeyConstraint(['report_id'], ['image_report.report_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_review_logs_id'), 'ocr_review_logs', ['id'], unique=False)
    op.create_table('pathology_ihc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('marker_name', sa.String(length=100), nullable=False, comment='标记物名称: ER, PR, HER2, Ki-67, TTF-1 等'),
    sa.Column('result', sa.String(length=50), nullable=True, comment='结果: 阳性/阴性/弱阳性/强阳性 等'),
    sa.Column('intensity', sa.String(length=20), nullable=True, comment='染色强度: +/++/+++'),
    sa.Column('percentage', sa.String(length=20), nullable=True, comment='阳性细胞百分比: 30%, >90%'),
    sa.ForeignKeyConstraint(['report_id'], ['pathology_report.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pathology_ihc_marker_name', 'pathology_ihc', ['marker_name'], unique=False)
    op.create_index('ix_pathology_ihc_report_id', 'pathology_ihc', ['report_id'], unique=False)
    op.create_table('leader_agent_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leader_session_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False, comment='专家标识'),
    sa.Column('agent_name', sa.String(length=100), nullable=False, comment='专家名称'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='success/failed'),
    sa.Column('content', sa.Text(), nullable=True, comment='分析内容'),
    sa.Column('error', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leader_session_id'], ['leader_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leader_session_id', 'sequence_number', name='uq_agent_result_seq')
    )
    op.create_index(op.f('ix_leader_agent_results_id'), 'leader_agent_results', ['id'], unique=False)
    op.create_index(op.f('ix_leader_agent_results_leader_session_id'), 'leader_agent_results', ['leader_session_id'], unique=False)
    op.create_table('leader_final_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leader_session_id', sa.Integer(), nullable=False),
    sa.Column('report', sa.Text(), nullable=False, comment='Markdown 格式'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leader_session_id'], ['leader_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leader_session_id')
    )
    op.create_index(op.f('ix_leader_final_reports_id'), 'leader_final_reports', ['id'], unique=False)
    op.create_table('leader_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leader_session_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False, comment='assessment/question/answer/team_config/progress/error/leader_thinking/leader_summarizing/execution_status/execution_stopped/web_search_result'),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leader_session_id'], ['leader_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leader_session_id', 'sequence_number', name='uq_leader_message_seq')
    )
    op.create_index(op.f('ix_leader_messages_id'), 'leader_messages', ['id'], unique=False)
    op.create_index(op.f('ix_leader_messages_leader_session_id'), 'leader_messages', ['leader_session_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user/assistant'),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('leader_session_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=True, comment='normal/leader_thinking/leader_question/agent_result/leader_summary'),
    sa.Column('is_review_mode', sa.Boolean(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['leader_session_id'], ['leader_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leader_messages_leader_session_id'), table_name='leader_messages')
    op.drop_index(op.f('ix_leader_messages_id'), table_name='leader_messages')
    op.drop_table('leader_messages')
    op.drop_index(op.f('ix_leader_final_reports_id'), table_name='leader_final_reports')
    op.drop_table('leader_final_reports')
    op.drop_index(op.f('ix_leader_agent_results_leader_session_id'), table_name='leader_agent_results')
    op.drop_index(op.f('ix_leader_agent_results_id'), table_name='leader_agent_results')
    op.drop_table('leader_agent_results')
    op.drop_index('ix_pathology_ihc_report_id', table_name='pathology_ihc')
    op.drop_index('ix_pathology_ihc_marker_name', table_name='pathology_ihc')
    op.drop_table('pathology_ihc')
    op.drop_index(op.f('ix_ocr_review_logs_id'), table_name='ocr_review_logs')
    op.drop_table('ocr_review_logs')
    op.drop_index('ix_medication_log_patient_date', table_name='medication_log')
    op.drop_index('ix_medication_log_med_date_slot', table_name='medication_log')
    op.drop_index('ix_medication_log_med_date', table_name='medication_log')
    op.drop_index(op.f('ix_medication_log_id'), table_name='medication_log')
    op.drop_index(op.f('ix_medication_log_account_id'), table_name='medication_log')
    op.drop_table('medication_log')
    op.drop_index('ix_medical_check_detail_status', table_name='medical_check_detail')
    op.drop_index(op.f('ix_medical_check_detail_medical_detail_id'), table_name='medical_check_detail')
    op.drop_index('idx_medical_check_detail_medical_id', table_name='medical_check_detail')
    op.drop_index('idx_medical_check_detail_index_id', table_name='medical_check_detail')
    op.drop_table('medical_check_detail')
    op.drop_index('ix_leader_sessions_patient_id', table_name='leader_sessions')
    op.drop_index(op.f('ix_leader_sessions_id'), table_name='leader_sessions')
    op.drop_index('ix_leader_sessions_conversation_state', table_name='leader_sessions')
    op.drop_index(op.f('ix_leader_sessions_conversation_id'), table_name='leader_sessions')
    op.drop_table('leader_sessions')
    op.drop_index(op.f('ix_knowledge_access_log_log_id'), table_name='knowledge_access_log')
    op.drop_index('idx_knowledge_access_log_doc', table_name='knowledge_access_log')
    op.drop_index('idx_knowledge_access_log_account', table_name='knowledge_access_log')
    op.drop_table('knowledge_access_log')
    op.drop_index(op.f('ix_consultation_external_sessions_status'), table_name='consultation_external_sessions')
    op.drop_index(op.f('ix_consultation_external_sessions_provider'), table_name='consultation_external_sessions')
    op.drop_index(op.f('ix_consultation_external_sessions_id'), table_name='consultation_external_sessions')
    op.drop_index(op.f('ix_consultation_external_sessions_conversation_id'), table_name='consultation_external_sessions')
    op.drop_index('ix_consultation_external_provider_status', table_name='consultation_external_sessions')
    op.drop_table('consultation_external_sessions')
    op.drop_index('idx_user_index_group_unique', table_name='user_index_group')
    op.drop_table('user_index_group')
    op.drop_index(op.f('ix_timeline_events_patient_id'), table_name='timeline_events')
    op.drop_index('ix_timeline_events_patient_date', table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_share_token_token'), table_name='share_token')
    op.drop_index(op.f('ix_share_token_id'), table_name='share_token')
    op.drop_table('share_token')
    op.drop_index(op.f('ix_record_summary_summary_id'), table_name='record_summary')
    op.drop_table('record_summary')
    op.drop_table('prompt_config')
    op.drop_index(op.f('ix_pathology_report_report_id'), table_name='pathology_report')
    op.drop_index(op.f('ix_pathology_report_patient_id'), table_name='pathology_report')
    op.drop_table('pathology_report')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_index('idx_medications_start_date', table_name='medications')
    op.drop_index('idx_medications_patient_status', table_name='medications')
    op.drop_index('idx_medications_account', table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_medical_record_record_id'), table_name='medical_record')
    op.drop_index(op.f('ix_medical_record_patient_id'), table_name='medical_record')
    op.drop_table('medical_record')
    op.drop_index(op.f('ix_medical_exam_exam_id'), table_name='medical_exam')
    op.drop_index('idx_medical_exam_patient_date', table_name='medical_exam')
    op.drop_table('medical_exam')
    op.drop_index(op.f('ix_medical_check_medical_id'), table_name='medical_check')
    op.drop_index('idx_medical_check_patient_date', table_name='medical_check')
    op.drop_table('medical_check')
    op.drop_index(op.f('ix_knowledge_document_doc_id'), table_name='knowledge_document')
    op.drop_index('idx_knowledge_document_category', table_name='knowledge_document')
    op.drop_index('idx_knowledge_document_account', table_name='knowledge_document')
    op.drop_table('knowledge_document')
    op.drop_index(op.f('ix_image_report_report_id'), table_name='image_report')
    op.drop_index('idx_image_report_patient_ocr', table_name='image_report')
    op.drop_index('idx_image_report_patient_category', table_name='image_report')
    op.drop_index('idx_image_report_dedup', table_name='image_report')
    op.drop_table('image_report')
    op.drop_index(op.f('ix_follow_up_reminder_id'), table_name='follow_up_reminder')
    op.drop_index('idx_follow_up_patient_status', table_name='follow_up_reminder')
    op.drop_table('follow_up_reminder')
    op.drop_index('ix_conversations_user_updated', table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_share_token'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_patient_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_category'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_wechat_binding_binding_id'), table_name='wechat_binding')
    op.drop_table('wechat_binding')
    op.drop_index('idx_user_favorite_unique', table_name='user_favorite_index')
    op.drop_table('user_favorite_index')
    op.drop_index(op.f('ix_patient_patient_id'), table_name='patient')
    op.drop_index(op.f('ix_patient_id_card_hash'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_notification_notification_id'), table_name='notification')
    op.drop_index('idx_notification_account_read', table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_knowledge_category_category_id'), table_name='knowledge_category')
    op.drop_index('idx_knowledge_category_parent', table_name='knowledge_category')
    op.drop_index('idx_knowledge_category_account', table_name='knowledge_category')
    op.drop_table('knowledge_category')
    op.drop_index(op.f('ix_medical_index_index_id'), table_name='medical_index')
    op.drop_index('idx_medical_index_code', table_name='medical_index')
    op.drop_index('idx_medical_index_category', table_name='medical_index')
    op.drop_index('idx_medical_index_active', table_name='medical_index')
    op.drop_table('medical_index')
    op.drop_index(op.f('ix_login_account_account_id'), table_name='login_account')
    op.drop_table('login_account')
    op.drop_table('llm_configs')
    op.drop_index(op.f('ix_knowledge_config_config_id'), table_name='knowledge_config')
    op.drop_index('idx_knowledge_config_key', table_name='knowledge_config')
    op.drop_table('knowledge_config')
    op.drop_index(op.f('ix_image_category_category_id'), table_name='image_category')
    op.drop_table('image_category')
    op.drop_table('agentteams_integration_configs')
    # ### end Alembic commands ###
